Repository TUMS-SAU/SAU-0.5, pull requests merged in 2024-02, with the labels that each got.

#31 feat- merge 1
  Assets/Undead Survivor/Script/GameManager.cs
  Assets/Undead Survivor/Script/Gear.cs
  Assets/Undead Survivor/Script/Item.cs
  Assets/Undead Survivor/Script/ItemData.cs
  Assets/Undead Survivor/Script/Weapon.cs
Labels: bug, enhancement

#33 Feat/#30 enhancement merge
  Assets/Scenes/SampleScene.unity
  Assets/Undead Survivor/Data/Alcohol.asset
  Assets/Undead Survivor/Data/Alcohol.asset.meta
  Assets/Undead Survivor/Data/Chicken.asset
  Assets/Undead Survivor/Data/Chicken.asset.meta
  Assets/Undead Survivor/Data/Coffee.asset
  Assets/Undead Survivor/Data/Coffee.asset.meta
  Assets/Undead Survivor/Data/Cookie.asset
  Assets/Undead Survivor/Data/Cookie.asset.meta
  Assets/Undead Survivor/Data/Ecobag.asset
  Assets/Undead Survivor/Data/Friendshield.asset
  Assets/Undead Survivor/Data/Item 1.asset
  Assets/Undead Survivor/Prefabs/Bullet 0.prefab
  Assets/Undead Survivor/Script/Item.cs
  Assets/Undead Survivor/Script/ItemData.cs
  Assets/Undead Survivor/Script/Weapon.cs
  Assets/Undead Survivor/Sprites/SpriteforSAU/americo.png
  Assets/Undead Survivor/Sprites/SpriteforSAU/americo.png.meta
  Assets/Undead Survivor/Sprites/SpriteforSAU/beer.png
  Assets/Undead Survivor/Sprites/SpriteforSAU/beer.png.meta
  Assets/Undead Survivor/Sprites/SpriteforSAU/쿠키.png
  Assets/Undead Survivor/Sprites/SpriteforSAU/쿠키.png.meta
Labels: bug, enhancement

#51 Feat: 에코백으로 무기 시작
  Assets/Undead Survivor/Data/Ecobag.asset
  Assets/Undead Survivor/Data/Friendshield.asset
  Assets/Undead Survivor/Script/GameManager.cs
  Assets/Undead Survivor/Script/Weapon.cs
Labels: enhancement

#55 Style: Dead Sprite
  Assets/Undead Survivor/Animations/AcFreshman.overrideController
  Assets/Undead Survivor/Animations/Dead_Freshman.anim
  Assets/Undead Survivor/Animations/Dead_Freshman.anim.meta
  Assets/Undead Survivor/Animations/Dead_Freshman1.anim
  Assets/Undead Survivor/Animations/Dead_Freshman1.anim.meta
  Assets/Undead Survivor/Sprites/Sau-ch/Sau-ch/Death.2.2/Death.2_0001.png.meta
  Assets/Undead Survivor/Sprites/Sau-ch/Sau-ch/Death.2.2/Death.2_0002.png.meta
  Assets/Undead Survivor/Sprites/Sau-ch/Sau-ch/Death.2.2/Death.2_0003.png.meta
  Assets/Undead Survivor/Sprites/Sau-ch/Sau-ch/Death.2.2/Death.2_0004.png.meta
  Assets/Undead Survivor/Sprites/Sau-ch/Sau-ch/Death.2.2/Death.2_0005.png.meta
  Assets/Undead Survivor/Sprites/Sau-ch/Sau-ch/Death.2.2/Death.2_0006.png.meta
  Assets/Undead Survivor/Sprites/Sau-ch/Sau-ch/Death.2.2/Death.2_0007.png.meta
Labels: enhancement

#57 Fix: 브금 수정
  Assets/Scenes/Start.unity
  Assets/Undead Survivor/Script/SceneAudioController.cs
Labels: bug
